FROM node:18 AS build

WORKDIR /app

# Copies both package and package-lock using *
COPY ./backend/package.json ./
COPY ./backend/package-lock.json ./

RUN npm install

COPY ./backend ./

EXPOSE 4001

CMD ["npm", "run", "start:production"]
