apiVersion: apps/v1
kind: Deployment
metadata:
  name: volunteer-tracker-backend
spec:
  replicas: 1
  selector: # Uses labels to match the pods
    matchLabels:
      app: volunteer-tracker-backend 
  template: # Blueprint for the Pods that Kubernetes will create
    metadata:
      labels:
        app: volunteer-tracker-backend # This label is added to each pod
    spec:
      containers:
        - env:
            - name: API_URL
              value: http://localhost:4001
            - name: CONNECTION_URL
              value: mongodb://db:27017/volunteer-tracker
            - name: PORT
              value: "4001"
          image: volunteer-tracker-backend # Load the local docker image into minikube using eval $(minikube docker-env)
          name: volunteer-tracker-backend
          ports:
            - containerPort: 4001
              protocol: TCP
          imagePullPolicy: Never # Prevents pulling from hub, just using local image
      restartPolicy: Always
